spring:
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: microservice-provider-user

server:
  port: 8000

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://server01:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10