spring:
  application:
    name: microservice-discovery-eureka-ha

eureka:
  client:
    service-url:
      defaultZone: http://server01:8761/eureka/,http://server02:8762/eureka/
---
server:
  port: 8761
spring:
  profiles: server01
eureka:
  instance:
    hostname: server01

---
server:
  port: 8762
spring:
  profiles: server02
eureka:
  instance:
    hostname: server02