server:
  port: 8010

logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
spring:
  zipkin:
    base-url: http://172.20.10.3:9411
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: simple-consumer-user