spring:
  jpa:
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://172.20.10.3:9411
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8000
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
