server:
  port: 9999

management:
  security:
    enabled: false

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://server01:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: Spring Boot Admin Console
